### ISSUE TITLE
Bug: Hex color in list

### ISSUE THREAD

**Issue by NoltoxGit** [MackenzieMolloy/ShopGUIPlus-SellGUI#11]
----
Hellow !
I found a bug with your plugin when a item use [hex colors in list](https://gyazo.com/1ae3c618367c70dd6591115a459fdbc5)  after sell.

Information:
Jar: Purpur-1786 (MC: 1.19.2)
Java: 17.0.4.1
ShopGUIPlus: 1.78.0
ShopGUIPlus-SellGUI: 1.1.5

-----

~ Noltox ~

**Comment by MackenzieMolloy** [comment]
Could you please highlight what the is issue? As the screenshot provided seems perfectly fine to me.

**Comment by NoltoxGit** [comment]
> Could you please highlight what the is issue? As the screenshot provided seems perfectly fine to me.

How can I make it more highlight?

**Comment by NoltoxGit** [comment]
The screen is not correct because during the sale, the items sold use a HEX color.
And your plugin does not support this color format in the hover message of the sale summary. 
Here is an example in [video](https://youtu.be/BBZcHKDqQWU).

**Comment by MackenzieMolloy** [comment]
Thank you for your clarification, this is indeed a bug and I will get it fixed shortly.

**Comment by NoltoxGit** [comment]
Hellow,
Any news about the bug fix?

**Comment by NoltoxGit** [comment]
Hellow !
What's new about this issue?

**Comment by NoltoxGit** [comment]
I don't use this plugin anymore, so I can close this issue. Thank you very much for your help
