### ISSUE TITLE
[CRITICAL BUG] Sell GUI Dupe Glitch utilizing Bundles

### ISSUE THREAD

**Issue by JosTheDude** [MackenzieMolloy/ShopGUIPlus-SellGUI#14]
This issue is pertaining to a dupe glitch found using bundles with ShopGUI+ Sell GUI.

Issue was reported by a moderator on our team, essentially:
`You basically right click any item you want to dupe with this and it will dupe any stackable item to 64 instantly and if you right click any armor it slowly adds up to a stack of 64`

Videos of the dupe from the player's perspective: 

https://github.com/MackenzieMolloy/ShopGUIPlus-SellGUI/assets/43651265/74030616-2c80-4302-aa0f-2696dcf12cb7

https://github.com/MackenzieMolloy/ShopGUIPlus-SellGUI/assets/43651265/d47fe84e-671d-400f-92f4-c21148179db7

Both videos are using the latest version of ShopGUI+ and ShopGUI+ Sell GUI.

**Comment by JosTheDude** [comment]
Member of the team who found the issue: @coswics

**Comment by JosTheDude** [comment]
Ah, this related to a Minecraft Bug at the core.

Recommendation would just be to blacklist overfilled bundles from being put into the GUI

I'll work on a PR tomorrow once I have the time.. but it is an mc bug so... unsure if there's really a point, but still.

https://bugs.mojang.com/browse/MC-225381

**Comment by PedroMPagani** [comment]
Why is this even allowed to be publicly here when this can destroy servers in seconds hugh

**Comment by JosTheDude** [comment]
> Why is this even allowed to be publicly here when this can destroy servers in seconds hugh

Bundles are an unreleased item so it's mainly to prevent social engineering as the bug was already being abused; so.

No security policy to be able to private issue it (and this plugin didn't have a Discord available) so... all that was mentioned on the page was to get in touch :P

**Comment by JosTheDude** [comment]
It was already being utilized on a few servers using bundles in some ways and as it was a public bug on MC, people we're utilizing social engineering to get on full bundle to dupe already; so figured it'd be good to open the issue as a whole. Though, now that it was discovered it was an mc bug... unsure if there's really a point.

But awareness regarding bundles has been spread around and due to Mojang having a history of not fixing unreleased items, figured it'd be alright to keep it out there to hopefully get it fixed here and in other plugins.

**Comment by xyzeva** [comment]
This is NOT, how a security issue is meant to be reported, please see [hackerone's disclosure guidelines](https://www.hackerone.com/disclosure-guidelines).

Bundles are also a unsupported item, and not solidified out, and Mojang has made it clear for that. Survival for bundles arent meant to be used.

**Comment by JosTheDude** [comment]
> [xyzeva](/xyzeva)

My mistake in entirety as I didn't realize it was an mc-based bug. I can't delete this issue, however, I've informed a few communities about the issues with bundles (since some are using them) and asked mackenzie to delete it rather than close.

**Comment by MackenzieMolloy** [comment]
As stated in your replies, this is an issue with Minecraft itself and not SellGUI. I was unaware this item was even accessible in the game, I thought they completely strapped it, and with that said I will not be providing a patch so-to-speak for this issue
