### ISSUE TITLE
Donate items

### ISSUE THREAD

**Issue by Ovaredge** [MackenzieMolloy/ShopGUIPlus-SellGUI#16]
How do I make it possible to sell donated items, for example, privates from Protection Stone or ExecutableItems?

**Comment by MackenzieMolloy** [comment]
Please refer to BRC's Documentation for ShopGUIPlus help or their Support Discord server for help on listing items for sale. 
https://docs.brcdev.net/#/
https://discord.brcdev.net/

SellGUI does not have any functionality to list items, it gets all the prices from ShopGUIPlus.
