### ISSUE TITLE
SellGUI extreme bug and low tps lag

### ISSUE THREAD

**Issue by EarthCraftOfficial** [MackenzieMolloy/ShopGUIPlus-SellGUI#7]
Very good plugin but I had to remove it due to a game breaking bug. Once you open the GUI and put items in it, close it to sell it. the tps goes down by around 2-6.

To recreate the bug, do /tpsbar. and then open the sellgui, put some items and close it to sell it. you will see the tps going down by a lot

This is probably caused by the Exitgui listener or when it calculates the number to your balance.

**Comment by MackenzieMolloy** [comment]
Resolved via Discord Ticket.

Note: Only Purpur appears to have this issue, and I have not been able to reproduce this. Try using Paper
